# <u>**Extract, Transform and Load (ETL)**</u>

This notebook is the initial step towards a standard data analytics workflow. Data quality is essential for effective Exploratory Data Analysis, Feature Engineering, Machine Learning Model development and dashboard visualisation. The data cleaning process requires thorough checks to ensure the integrity of the datasets before saving the transformations into a joined DataFrame. The steps taken in this notebook are:

- Load libraries and datasets

- Initial datasets review 

- Standardise column names 

- Identify missing, unique or duplicate values

- Ammend DataTypes 

- Add year columns for year-on-year analysis

- Join 2023-2024 and 2025-2025 datasets

- Drop identifiable information columns 

- Save DataFrame into clean data folder

ETL can reveal additional requirements during these dataset checks. This plan is based on common steps taught through Code Institute LMS content, tutor guidance and online resources, which are included in the credits section of the README. The built-in Visual Studio Code Copilot will also assist with fixing or modifying code and adding comments to streamline the process.

</b>

## <u>**Load Libraries and Data**</u>

Libraries - Pandas and Numpy - are imported. Raw datasets exported as CSV files from Excel sheets are loaded into two separate DataFrames using Pandas.

In [1]:
# Import libraries 
import pandas as pd
import numpy as np

# Read the CSV file into a DataFrame
df_24 = pd.read_csv('/Users/admin/Documents/Code Institute/ace_project/data/raw/2023_24_ace_raw.csv')
df_26 = pd.read_csv('/Users/admin/Documents/Code Institute/ace_project/data/raw/2025_26_ace_raw.csv')

# Check rows and columns in the DataFrames
print("Shape of df_24:", df_24.shape)
print("Shape of df_26:", df_26.shape)

Shape of df_24: (3085, 11)
Shape of df_26: (2369, 11)

</b>

### <u>**Intial DataFrame Review**</u>

Use <code>.info()</code> and <code>.head()</code> to conduct an initial review of both DataFrames. These methods help assess the datasets' structure, column names, data types, non-null values and the first few rows, providing an overview of the data before cleaning and transformation.

In [2]:
# Display information about df_24
df_24.info() 

# Display the first few rows of df_24
df_24.head()

<class 'pandas.DataFrame'>
RangeIndex: 3085 entries, 0 to 3084
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Recipient              3085 non-null   str
 1   Activity name          3085 non-null   str
 2   Award amount           3085 non-null   str
 3   Award date             3085 non-null   str
 4   Decision Month         3085 non-null   str
 5   Decision quarter       3085 non-null   str
 6   ACE Area               3085 non-null   str
 7   Local authority        3085 non-null   str
 8   Main discipline        3085 non-null   str
 9   Strand                 3085 non-null   str
 10  Time-Limited Priority  240 non-null    str
dtypes: str(11)
memory usage: 265.2 KB

,Recipient,Activity name,Award amount,Award date,Decision Month,Decision quarter,ACE Area,Local authority,Main discipline,Strand,Time-Limited Priority
0,Feelprime Ltd,Old Fire Station Digital,"£27,689",03-Apr-23,April,Q1,South West,"Bournemouth, Christchurch and Poole",Music,"£30,000 and below",Supporting Grassroots Live Music
1,Downtown Pompey,Sticky Floors and Palm Trees,"£29,623",03-Apr-23,April,Q1,South West,Portsmouth,Theatre,"£30,000 and below",NaN
2,Chew Valley Performing Arts,Autumn Fringe Festival 2023,"£25,256",03-Apr-23,April,Q1,South West,Bath and North East Somerset,Combined arts,"£30,000 and below",NaN
3,Upfest,Weston Wallz 2023,"£30,500",03-Apr-23,April,Q1,South West,"Bristol, City of",Visual arts,"£30,000 and below",NaN
4,Chloe Thurlow,"Haunt, Pray, Love","£20,060",03-Apr-23,April,Q1,South West,South Gloucestershire,Theatre,"£30,000 and below",NaN

In [3]:
# Display information about df_26
df_26.info()  

# Display the first few rows of df_26
df_26.head()

<class 'pandas.DataFrame'>
RangeIndex: 2369 entries, 0 to 2368
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Recipient              2369 non-null   str
 1   Activity name          2369 non-null   str
 2   Award amount           2369 non-null   str
 3   Award date             2369 non-null   str
 4   Decision Month         2369 non-null   str
 5   Decision quarter       2369 non-null   str
 6   ACE Area               2369 non-null   str
 7   Local authority        2368 non-null   str
 8   Main discipline        2369 non-null   str
 9   Strand                 2369 non-null   str
 10  Time-Limited Priority  224 non-null    str
dtypes: str(11)
memory usage: 203.7 KB

,Recipient,Activity name,Award amount,Award date,Decision Month,Decision quarter,ACE Area,Local authority,Main discipline,Strand,Time-Limited Priority
0,Window Wanderland CIC,"Community of practise, Wanderland Pilot","£33,522",01-Apr-25,April,Q1,South West,"Bristol, City of",Combined arts,"£30,000 and below",NaN
1,Cat and Mouse Theatre,Time Crime,"£27,461",01-Apr-25,April,Q1,South West,South Gloucestershire,Theatre,"£30,000 and below",NaN
2,London Borough of Ealing Libraries and communi...,Y-Our Story Visual Stories of Acton,"£27,000",01-Apr-25,April,Q1,London,Ealing,Libraries,"£30,000 and below",Universal Library Offers
3,Exmouth Festival,Exmouth Festival 2025,"£38,500",01-Apr-25,April,Q1,South West,East Devon,Combined arts,"Above £30,000",NaN
4,Crediton Heart Project,Crediton Heart Summer Arts Festival,"£15,135",01-Apr-25,April,Q1,South West,Mid Devon,Combined arts,"£30,000 and below",NaN

The outputs from <code>.info()</code> show that both DataFrames share the same column names but require text standardisation.

Missing values are present in both DataFrames. <code>df_24</code> contains 240 non-null values in the Time-Limited Priority column, while <code>df_26</code> contains 224 non-null values in the Time-Limited Priority column and one missing value in the Local Authority column.

All columns are currently stored as strings, requiring conversion to appropriate numerical, date-time and categorical data types to support analysis and visualisation in the EDA notebook.

The output from <code>.head()</code> reveals potentially identifiable information in the Recipient and Activity Name columns. These columns must be dropped to support ethical data handling and protect personal information.

</b>

## <u>**Standardise Column Names**</u>

Consistent column naming is essential for accessing columns across the EDA, Feature Engineering and ML Model notebooks. Standardise column names by removing leading and trailing whitespace using <code>.strip()</code>, replacing spaces or hyphens with underscores using <code>.replace()</code>, and converting text to lowercase using <code>.lower()</code>. These conventions improve code readability, maintain consistency and reduce errors when referencing columns across the workflow.

In [4]:
# Format column names df_24
df_24.columns = (df_24.columns
                 .str.strip()
                 .str.lower()
                 .str.replace(' ', '_')
                 .str.replace('-', '_'))

# Format column names df_26
df_26.columns = (df_26.columns
                 .str.strip()
                 .str.lower()
                 .str.replace(' ', '_')
                 .str.replace('-', '_'))

In [5]:
# Check column names 2023-2024
df_24.head()

,recipient,activity_name,award_amount,award_date,decision_month,decision_quarter,ace_area,local_authority,main_discipline,strand,time_limited_priority
0,Feelprime Ltd,Old Fire Station Digital,"£27,689",03-Apr-23,April,Q1,South West,"Bournemouth, Christchurch and Poole",Music,"£30,000 and below",Supporting Grassroots Live Music
1,Downtown Pompey,Sticky Floors and Palm Trees,"£29,623",03-Apr-23,April,Q1,South West,Portsmouth,Theatre,"£30,000 and below",NaN
2,Chew Valley Performing Arts,Autumn Fringe Festival 2023,"£25,256",03-Apr-23,April,Q1,South West,Bath and North East Somerset,Combined arts,"£30,000 and below",NaN
3,Upfest,Weston Wallz 2023,"£30,500",03-Apr-23,April,Q1,South West,"Bristol, City of",Visual arts,"£30,000 and below",NaN
4,Chloe Thurlow,"Haunt, Pray, Love","£20,060",03-Apr-23,April,Q1,South West,South Gloucestershire,Theatre,"£30,000 and below",NaN

In [6]:
# Check column names 2025-2026
df_24.head()

,recipient,activity_name,award_amount,award_date,decision_month,decision_quarter,ace_area,local_authority,main_discipline,strand,time_limited_priority
0,Feelprime Ltd,Old Fire Station Digital,"£27,689",03-Apr-23,April,Q1,South West,"Bournemouth, Christchurch and Poole",Music,"£30,000 and below",Supporting Grassroots Live Music
1,Downtown Pompey,Sticky Floors and Palm Trees,"£29,623",03-Apr-23,April,Q1,South West,Portsmouth,Theatre,"£30,000 and below",NaN
2,Chew Valley Performing Arts,Autumn Fringe Festival 2023,"£25,256",03-Apr-23,April,Q1,South West,Bath and North East Somerset,Combined arts,"£30,000 and below",NaN
3,Upfest,Weston Wallz 2023,"£30,500",03-Apr-23,April,Q1,South West,"Bristol, City of",Visual arts,"£30,000 and below",NaN
4,Chloe Thurlow,"Haunt, Pray, Love","£20,060",03-Apr-23,April,Q1,South West,South Gloucestershire,Theatre,"£30,000 and below",NaN

</b>

## <u>**Missing Values**</u>

### **Inspect Missing Values**

Missing values can affect the accuracy and interpretation of visualisations in the EDA. Depending on the chart type and visualisation tool, missing values may be excluded from calculations, appear as null or blank categories, or reduce the number of records represented. This can lead to incomplete comparisons, misleading totals or inaccurate summaries if missing data is not accounted for. In the ML Modelling notebook, NaN or blank values may also cause errors in certain tools and libraries during model training. 

To identify missing values in each column, use <code>.isna().sum()</code>. This helps determine where missing data occurs and informs decisions about appropriate handling during data cleaning.

In [7]:
# Check for missing values in df_24
df_24.isna().sum()

recipient                   0
activity_name               0
award_amount                0
award_date                  0
decision_month              0
decision_quarter            0
ace_area                    0
local_authority             0
main_discipline             0
strand                      0
time_limited_priority    2845
dtype: int64

The Time-Limited Priority column contains 2,854 missing values for awards received between 2023-2024. These values will not be replaced or removed at this stage because their meaning has not yet been established. 

Further research is required to determine whether missing values indicate that an award was not subject to a time-limited priority or whether the information was not recorded. Until the meaning is confirmed, the values will be preserved to avoid introducing assumptions or misrepresenting the original data. The final handling decision will be made during data cleaning once sufficient context is available.

In [8]:
# Check for missing values in df_26
df_26.isna().sum()

recipient                   0
activity_name               0
award_amount                0
award_date                  0
decision_month              0
decision_quarter            0
ace_area                    0
local_authority             1
main_discipline             0
strand                      0
time_limited_priority    2145
dtype: int64

Compared with the 2023-2024 DataFrame, the 2025-2026 DataFrame contains 2,145 missing values in the Time-Limited Priority column, alongside one missing value in the Local Authority column. The additional missing value in Local Authority requires investigation before transformation to determine whether the correct value can be recovered.

In [9]:
# Check for missing values in the "local_authority" column of df_26
df_26[df_26["local_authority"].isna()]

,recipient,activity_name,award_amount,award_date,decision_month,decision_quarter,ace_area,local_authority,main_discipline,strand,time_limited_priority
1328,Comics Cultural Impact Collective,NLPG O30 Oct25,"£37,000",17-Dec-25,December,Q3,North,NaN,Literature,"Above £30,000",NaN

According to the official Arts Council documentation place refers to a specific geographic area where a proposed intervention will take place:

>We define place as a specific geographic area of any scale (village, town, local authority, city or city region) where the proposed intervention will take place and where a cultural strategy (or similar) exists that covers the same geography. This could mean that an application might be for activity in a town or village that is covered by a cultural strategy for a wider district.

[National Lottery Project Grants Information Sheet](https://www.artscouncil.org.uk/sites/default/files/2023-09/Place%20Partnership%20projects%20and%20Project%20Grants%20-%20Information%20sheet.pdf)

The Arts Council's National Lottery Project Grants: Guidance Library confirms that missing values in the Time-Limited Priority column represent projects that are not time-limited. These values can therefore be treated as not applicable, rather than missing information.

[National Lottery Project Grants: Guidance Library](https://www.artscouncil.org.uk/ProjectGrants/national-lottery-project-grants-guidance-library#t-in-page-nav-5)

</b>

### **Handle Missing Values**

Replace the missing value in the 2025-2026 DataFrame's <code>local_authority</code> column with "Unknown". According to the Arts Council documentation, the recipient may operate across multiple local authorities, so assigning a specific authority could misrepresent the data.

In [10]:
# Replace missing value in the 'local_authority' column with 'Unknown'
df_26['local_authority'] = df_26['local_authority'].fillna('Unknown')

# Check for remaining missing values in df_26
df_26.isna().sum()

recipient                   0
activity_name               0
award_amount                0
award_date                  0
decision_month              0
decision_quarter            0
ace_area                    0
local_authority             0
main_discipline             0
strand                      0
time_limited_priority    2145
dtype: int64

Replace missing values in the <code>time_limited_priority</code> column of both the 2023-2024 and 2025-2026 DataFrames with "Not Time Limited Priority". Arts Council documentation confirms that time-limited priorities do not apply to all awards. This replacement preserves all records while distinguishing awards without a time-limited priority from those with a specified priority.

In [11]:
# Replace missing values in the 'time_limited_priority' columns
for df in [df_24, df_26]:
   df['time_limited_priority'] = (
       df['time_limited_priority']
       .fillna('Not Time-Limited Priority'))

# Check for remaining missing values in df_24 and df_26
print("Missing values in df_24 after replacement:")
print(df_24.isna().sum())
print("\nMissing values in df_26 after replacement:")
print(df_26.isna().sum())

Missing values in df_24 after replacement:
recipient                0
activity_name            0
award_amount             0
award_date               0
decision_month           0
decision_quarter         0
ace_area                 0
local_authority          0
main_discipline          0
strand                   0
time_limited_priority    0
dtype: int64

Missing values in df_26 after replacement:
recipient                0
activity_name            0
award_amount             0
award_date               0
decision_month           0
decision_quarter         0
ace_area                 0
local_authority          0
main_discipline          0
strand                   0
time_limited_priority    0
dtype: int64

</b>

## **<u>Duplicate Rows</u>**

Check for duplicate rows using <code>.duplicated().sum()</code> to identify and count repeated records in each DataFrame. This check helps prevent duplicate awards from inflating totals in the EDA and introducing bias into the ML Modelling notebook.

In [12]:
# Check for duplicates in df_24 and df_26
print("Duplicates in df_24:", df_24.duplicated().sum())
print("Duplicates in df_26:", df_26.duplicated().sum())

Duplicates in df_24: 0
Duplicates in df_26: 0

The output confirms that neither DataFrame contains duplicate rows. Therefore, no further action is required for duplicate removal during data cleaning.

<b>

## **<u>Unique Values Review</u>**

Review unique values in the <code>ace_area</code>, <code>local_authority</code>, <code>main_discipline</code>, <code>strand</code> and <code>time_limited_priority</code> columns using <code>.unique()</code> to identify inconsistencies. 

Standardise spelling, whitespace and capitalisation where necessary to ensure that identical categories are represented consistently. This prevents duplicate category labels from distorting group counts and filtering in visualisations.

In [13]:
""" ACE AREA """

# Check unique values in ace_area column in df_24
print("Unique values in 'ace_area' column of df_24:")
print(df_24['ace_area'].unique())    

# Check unique values in ace_area column in df_26
print("Unique values in 'ace_area' column of df_26:")
print(df_26['ace_area'].unique())

Unique values in 'ace_area' column of df_24:
<StringArray>
['South West', 'Midlands', 'London', 'South East', 'North']
Length: 5, dtype: str
Unique values in 'ace_area' column of df_26:
<StringArray>
['South West', 'London', 'Midlands', 'South East', 'North']
Length: 5, dtype: str

In [14]:
""" LOCAL AUTHORITY """

# Check unique values in the 'local_authority' column of df_26
print("Unique values in 'local_authority' column of df_26:")
print(df_26['local_authority'].unique())    

# Check unique values in the 'local_authority' column of df_24
print("Unique values in 'local_authority' column of df_24:")
print(df_24['local_authority'].unique())

Unique values in 'local_authority' column of df_26:
<StringArray>
[            'Bristol, City of',        'South Gloucestershire',
                       'Ealing',                   'East Devon',
                    'Mid Devon',                   'Wandsworth',
                    'Islington',                      'Hackney',
 'Bath and North East Somerset',                     'Tamworth',
 ...
                       'Melton',                    'Hertsmere',
                    'Wokingham',                      'Fenland',
                        'Powys',             'Scottish Borders',
                     'Stirling',                     'Havering',
                     'Bolsover',          'South Staffordshire']
Length: 282, dtype: str
Unique values in 'local_authority' column of df_24:
<StringArray>
['Bournemouth, Christchurch and Poole',                          'Portsmouth',
        'Bath and North East Somerset',                    'Bristol, City of',
               'South Gloucestershire',                              'Torbay',
                            'Cornwall',                     'Isles of Scilly',
                           'Eastleigh',                          'New Forest',
 ...
                          'Tewkesbury',                           'Brentwood',
                            'Hyndburn',                              'Bexley',
               'North East Derbyshire',                          'Spelthorne',
                  'East Staffordshire',                        'West Lindsey',
                            'Torridge',                       'Cannock Chase']
Length: 286, dtype: str

In [15]:
""" STRAND """

# Check unique values in the 'strand' column of df_26
print("Unique values in 'strand' column of df_26:")
print(df_26['strand'].unique())    

# Check unique values in the 'strand' column of df_24
print("Unique values in 'strand' column of df_24:")
print(df_24['strand'].unique())

Unique values in 'strand' column of df_26:
<StringArray>
[                        '£30,000 and below',
                             'Above £30,000',
             'Above £30,000 - Major Project',
 'Above £30,000 - Over £30k Touring project',
    'Above £30,000 - Over £100k application',
 'Above £30,000 - Place Partnership project']
Length: 6, dtype: str
Unique values in 'strand' column of df_24:
<StringArray>
[                             '£30,000 and below',
                                  'Above £30,000',
         'Above £30,000 - Over £100k application',
      'Above £30,000 - Over £30k Touring project',
      'Above £30,000 - Place Partnership project',
 'Above £30,000 - Nationally Significant project']
Length: 6, dtype: str

In [16]:
""" TIME LIMITED PRIORITY """

# Check unique values in the 'time_limited_priority' column of df_26
print("Unique values in 'time_limited_priority' column of df_26:")
print(df_26['time_limited_priority'].unique())    

# Check unique values in the 'time_limited_priority' column of df_24
print("Unique values in 'time_limited_priority' column of df_24:")
print(df_24['time_limited_priority'].unique())

Unique values in 'time_limited_priority' column of df_26:
<StringArray>
[               'Not Time-Limited Priority',
                 'Universal Library Offers',
                    'Unlocking Collections',
              'Supporting Grassroots Music',
 'Research and Development for Individuals']
Length: 5, dtype: str
Unique values in 'time_limited_priority' column of df_24:
<StringArray>
['Supporting Grassroots Live Music',        'Not Time-Limited Priority',
            'Unlocking Collections',      'Supporting Grassroots Music',
         'Universal Library Offers']
Length: 5, dtype: str

### **Summary**

The output for each column indicates that no further text standardisation is required. However, differences exist between the 2023-2024 and 2025-2026 DataFrames in the <code>local_authority</code>, <code>strand</code> and <code>time_limited_priority</code> columns.

These differences are expected, as Arts Council documentation indicates that its funding strategies and priorities may change over time, affecting the available categories for <code>strand</code> and <code>time_limited_priority</code>.

The <code>local_authority</code> column contains numerous distinct values due to the granular nature of local authority boundaries. Despite this, the categories remain useful for grouping and counting awards distributed across local authorities.

</b>

## **<u>Convert DataTypes</u>**

Data consistency is essential for accurate visualisations in the EDA notebook. Review the data types in each DataFrame using <code>.dtypes</code> to identify columns that require conversion to numerical, date-time or categorical types.

The initial review identified that both DataFrames contain mostly categorical columns, alongside one numerical column and one date-time column, all initially stored as strings. Converting these columns to appropriate data types will support accurate analysis and visualisation in subsequent notebooks.

In [17]:
# Print DataTypes for 2023-2024
print("Data types for df_24:")
print(df_24.dtypes)

# Print DataTypes for 2025-2026
print("\nData types for df_26:")
print(df_26.dtypes)

Data types for df_24:
recipient                str
activity_name            str
award_amount             str
award_date               str
decision_month           str
decision_quarter         str
ace_area                 str
local_authority          str
main_discipline          str
strand                   str
time_limited_priority    str
dtype: object

Data types for df_26:
recipient                str
activity_name            str
award_amount             str
award_date               str
decision_month           str
decision_quarter         str
ace_area                 str
local_authority          str
main_discipline          str
strand                   str
time_limited_priority    str
dtype: object

</b >

### **Award Amount**

Similar to standardising column names in the previous section, use <code>.replace()</code> and <code>.strip()</code> to remove unwanted symbols and leading or trailing whitespace from numerical values. This helps prevent <code>ValueError</code> exceptions caused by invalid string literals during conversion. Convert the cleaned string values to the integer data type using <code>.astype(int)</code>.

In [18]:
# Clean and convert the 'award_amount' column in df_24
df_24["award_amount"] = (df_24["award_amount"]
                         .str.replace(',','')
                         .str.replace('£','')
                         .str.strip()
                         .astype(int))


# Clean and convert the 'award_amount' column in df_26
df_26["award_amount"] = (df_26["award_amount"]
                         .str.replace(',','')
                         .str.replace('£','')
                         .str.strip()
                         .astype(int))


# Check the data type of the 'award_amount' column
print("Data type df_24:", df_24["award_amount"].dtype) 
print("Data type df_26:", df_26["award_amount"].dtype)

Data type df_24: int64
Data type df_26: int64

</b>

### **Date-Time**

Convert the <code>award_date</code> column from the string data type to the datetime data type in both DataFrames using <code>pd.to_datetime()</code>. Check that the conversion is successful to ensure dates can be processed correctly.

Create a separate year column by extracting the year from <code>award_date</code> using <code>.dt.year</code>. This enables easier filtering, grouping and year-on-year comparisons in the EDA and dashboard visualisations.

In [20]:
# Convert the award_date column to datetime for both DataFrames
for data in (df_24, df_26):
    data['award_date'] = pd.to_datetime(
        data['award_date'],
        errors='coerce'
    )
    # Extract the award year from the datetime values
    data['award_year'] = (
        data['award_date']
        .dt.year
        .astype('Int64')
    )

Standardise the date format and handle invalid dates safely by using <code>errors='coerce'</code> within <code>pd.to_datetime()</code>. Invalid dates are converted to <code>NaT</code> (Not a Time), allowing the conversion to continue without raising an error. These missing date-time values can then be identified and investigated during data cleaning.

In [21]:
# Check the first few rows of df_24 to verify the changes
df_24.head()

,recipient,activity_name,award_amount,award_date,decision_month,decision_quarter,ace_area,local_authority,main_discipline,strand,time_limited_priority,award_year
0,Feelprime Ltd,Old Fire Station Digital,27689,2023-04-03,April,Q1,South West,"Bournemouth, Christchurch and Poole",Music,"£30,000 and below",Supporting Grassroots Live Music,2023
1,Downtown Pompey,Sticky Floors and Palm Trees,29623,2023-04-03,April,Q1,South West,Portsmouth,Theatre,"£30,000 and below",Not Time-Limited Priority,2023
2,Chew Valley Performing Arts,Autumn Fringe Festival 2023,25256,2023-04-03,April,Q1,South West,Bath and North East Somerset,Combined arts,"£30,000 and below",Not Time-Limited Priority,2023
3,Upfest,Weston Wallz 2023,30500,2023-04-03,April,Q1,South West,"Bristol, City of",Visual arts,"£30,000 and below",Not Time-Limited Priority,2023
4,Chloe Thurlow,"Haunt, Pray, Love",20060,2023-04-03,April,Q1,South West,South Gloucestershire,Theatre,"£30,000 and below",Not Time-Limited Priority,2023

Initially, the built-in Copilot modified the code to remove the timestamp using <code>.normalize()</code>. However, this method only resets the time to midnight and does not remove the time component. The appropriate method is <code>.dt.date</code>, which extracts the date without the timestamp.

As extracting the year requires the datetime data type, create the year column using <code>.dt.year</code> before applying <code>.dt.date</code>. This preserves the ability to extract the year while removing the timestamp from the date column.

In [22]:
# Remove time from award_date column in df_24 and df_26
df_24['award_date'] = df_24['award_date'].dt.date
df_26['award_date'] = df_26['award_date'].dt.date

In [23]:
# Check the first few rows of df_24 to verify the changes
df_24.head()

,recipient,activity_name,award_amount,award_date,decision_month,decision_quarter,ace_area,local_authority,main_discipline,strand,time_limited_priority,award_year
0,Feelprime Ltd,Old Fire Station Digital,27689,2023-04-03,April,Q1,South West,"Bournemouth, Christchurch and Poole",Music,"£30,000 and below",Supporting Grassroots Live Music,2023
1,Downtown Pompey,Sticky Floors and Palm Trees,29623,2023-04-03,April,Q1,South West,Portsmouth,Theatre,"£30,000 and below",Not Time-Limited Priority,2023
2,Chew Valley Performing Arts,Autumn Fringe Festival 2023,25256,2023-04-03,April,Q1,South West,Bath and North East Somerset,Combined arts,"£30,000 and below",Not Time-Limited Priority,2023
3,Upfest,Weston Wallz 2023,30500,2023-04-03,April,Q1,South West,"Bristol, City of",Visual arts,"£30,000 and below",Not Time-Limited Priority,2023
4,Chloe Thurlow,"Haunt, Pray, Love",20060,2023-04-03,April,Q1,South West,South Gloucestershire,Theatre,"£30,000 and below",Not Time-Limited Priority,2023

In [24]:
# Check the first few rows of df_26 to verify the changes
df_26.head()

,recipient,activity_name,award_amount,award_date,decision_month,decision_quarter,ace_area,local_authority,main_discipline,strand,time_limited_priority,award_year
0,Window Wanderland CIC,"Community of practise, Wanderland Pilot",33522,2025-04-01,April,Q1,South West,"Bristol, City of",Combined arts,"£30,000 and below",Not Time-Limited Priority,2025
1,Cat and Mouse Theatre,Time Crime,27461,2025-04-01,April,Q1,South West,South Gloucestershire,Theatre,"£30,000 and below",Not Time-Limited Priority,2025
2,London Borough of Ealing Libraries and communi...,Y-Our Story Visual Stories of Acton,27000,2025-04-01,April,Q1,London,Ealing,Libraries,"£30,000 and below",Universal Library Offers,2025
3,Exmouth Festival,Exmouth Festival 2025,38500,2025-04-01,April,Q1,South West,East Devon,Combined arts,"Above £30,000",Not Time-Limited Priority,2025
4,Crediton Heart Project,Crediton Heart Summer Arts Festival,15135,2025-04-01,April,Q1,South West,Mid Devon,Combined arts,"£30,000 and below",Not Time-Limited Priority,2025

</b>

### **Categorical**

Categorical columns contain a finite set of unique values representing distinct groups or categories. Use <code>.astype("category")</code> to convert string columns into the categorical data type, improving data consistency and supporting efficient grouping and analysis in subsequent notebooks.

In [25]:
# Group categorical columns for conversion to 'category' data type
categorical_cols = [
    "main_discipline",
    "strand",
    "time_limited_priority",
    "ace_area"
]

# Convert the categorical columns
for df in [df_24, df_26]:
    for col in categorical_cols:
        if col in df.columns:
            df[col] = df[col].astype("category")

In [26]:
# Check the data types of the categorical columns in df_24
df_24.dtypes

recipient                     str
activity_name                 str
award_amount                int64
award_date                 object
decision_month                str
decision_quarter              str
ace_area                 category
local_authority               str
main_discipline          category
strand                   category
time_limited_priority    category
award_year                  Int64
dtype: object

In [27]:
# Check the data types of the categorical columns in df_24
df_24.dtypes

# Check the data types of the categorical columns in df_26
df_26.dtypes

recipient                     str
activity_name                 str
award_amount                int64
award_date                 object
decision_month                str
decision_quarter              str
ace_area                 category
local_authority               str
main_discipline          category
strand                   category
time_limited_priority    category
award_year                  Int64
dtype: object

The <code>time_limited_priority</code> column remained as a string during the initial data type conversion. Missing values had been identified during the initial review and were investigated alongside duplicate and unique values before attempting further conversion.

During missing-value handling, a hyphen in the <code>time_limited_priority</code> column name was replaced with an underscore in the Standardise Column Names section. This highlights the importance of standardising column names at the beginning of the ETL process to maintain consistency and prevent errors in subsequent transformations.

</b>

## **<u>Anonymisation</u>**

Remove the <code>recipient</code> and <code>activity_name</code> columns using <code>.drop()</code>, as they contain potentially identifiable information and are not required for the EDA, Feature Engineering, ML Modelling notebooks or dashboard visualisations. This transformation supports ethical data handling by reducing the risk of exposing identifiable information and retaining only relevant features for further analysis.

In [28]:
# Remove identifiers from both DataFrames
df_24 = df_24.drop(columns=['recipient', 'activity_name'])
df_26 = df_26.drop(columns=['recipient', 'activity_name'])

In [29]:
# Check columns after dropping identifiers
print("Columns in df_24 after dropping identifiers:", df_24.columns)
print("Columns in df_26 after dropping identifiers:", df_26.columns)

Columns in df_24 after dropping identifiers: Index(['award_amount', 'award_date', 'decision_month', 'decision_quarter',
       'ace_area', 'local_authority', 'main_discipline', 'strand',
       'time_limited_priority', 'award_year'],
      dtype='str')
Columns in df_26 after dropping identifiers: Index(['award_amount', 'award_date', 'decision_month', 'decision_quarter',
       'ace_area', 'local_authority', 'main_discipline', 'strand',
       'time_limited_priority', 'award_year'],
      dtype='str')

</b>

## **<u>Join DataFrames</u>**

Combine the cleaned 2023-2024 and 2025-2026 National Lottery Project Grants DataFrames into a single DataFrame using <code>pd.concat()</code> with <code>ignore_index=True</code>. The resulting DataFrame contains records from both funding periods with consistent column names and a continuous index, providing a unified dataset for the Exploratory Data Analysis, Feature Engineering, ML Model notebooks and Tableau Dashboard.

In [30]:
# Concatenate the two DataFrames into a single DataFrame
df_combined = pd.concat([df_24, df_26], ignore_index=True)

# Check the shape of the combined DataFrame
print("Shape of combined DataFrame:", df_combined.shape)

# Check the first few rows of the combined DataFrame
df_combined.head()

Shape of combined DataFrame: (5454, 10)

,award_amount,award_date,decision_month,decision_quarter,ace_area,local_authority,main_discipline,strand,time_limited_priority,award_year
0,27689,2023-04-03,April,Q1,South West,"Bournemouth, Christchurch and Poole",Music,"£30,000 and below",Supporting Grassroots Live Music,2023
1,29623,2023-04-03,April,Q1,South West,Portsmouth,Theatre,"£30,000 and below",Not Time-Limited Priority,2023
2,25256,2023-04-03,April,Q1,South West,Bath and North East Somerset,Combined arts,"£30,000 and below",Not Time-Limited Priority,2023
3,30500,2023-04-03,April,Q1,South West,"Bristol, City of",Visual arts,"£30,000 and below",Not Time-Limited Priority,2023
4,20060,2023-04-03,April,Q1,South West,South Gloucestershire,Theatre,"£30,000 and below",Not Time-Limited Priority,2023

</b>

## **<u>Save Clean DataFrame</u>**

The final step is to save the <code>df_combined</code> DataFrame as <code>cleaned_data.csv</code> in the <code>data/clean/</code> folder using <code>.to_csv()</code> with <code>index=False</code> to prevent the DataFrame index from being saved as an additional column. This clean dataset will be used in the Exploratory Data Analysis, Feature Engineering notebooks and Tableau Dashboard.

In [ ]:
# Save the cleaned DataFrame as a new CSV file
df_combined.to_csv("cleaned_data.csv", index=False)